### ISSUE TITLE
Specify the model changes required to implement Configurable metadata framework

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/pass-data-model#55]
For this ticket, please review the needs from various components with in CMF to come up with the specification for data model changes that are required. 

Please elaborate on the impact of the model changes on existing code modules and recommend ways to accommodate the impacts.

Additionally, please describe in sequential steps how this model change should be rolled out in to the codebase in concert with the CMF feature.

**Comment by birkland** [comment]
https://docs.google.com/document/d/16tx-zcNBwcfEXd5VHKQoKEetza_PGUNTo6-Aj2_K8Ds/edit#
