### ISSUE TITLE
Add effectivePolicies to model

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/pass-data-model#56]
- [x] Update the PASS context to add Submission.effectivePolicies (depending on policy service impl) 
- [x] Update the PASS indexer to add Submission.effectivePolicies (depending on policy service impl) 
- [x] Update Fedora image to bake in new context (depending on policy service impl) → 1hr -2 days LE

**Comment by htpvu** [comment]
@birkland looks like this ticket is done. Can this ticket be closed?

**Comment by birkland** [comment]
Yes, the stated work is complete
