### ISSUE TITLE
Resolve bidirectional relationships and limit embedded URI lists in model

### ISSUE THREAD

**Issue by karenhanson** [OA-PASS/pass-data-model#9]
Several places in the model have bidirectional connections e.g. Submissions contains a list of Grants, and Grants contains a list of Submissions. This stems from some requirements in the Ember model and leads to complexity in updating records. Ideally one to many relationships would be the many referencing the one (e.g. Journal entity points to Publisher) or for many-to-many be in the direction that will minimize the need to maintain lists within records (e.g. Submissions should reference related Grants rather than Grants referencing the list of Submissions.

**Comment by markpatton** [comment]
On the ember side this is dependent on implementing Store.query.

**Comment by karenhanson** [comment]
PR #21 documents changes, these need to be reflected in context and applied to all systems affected.

**Comment by karenhanson** [comment]
Closed by PR #24 & #25
